In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\\programming\\programming\\python\\age&genderdetection\\yolov9\\Resume History\\Elytespark Major Project\\IBM-Healthcare-AI\\data\\raw\\Data Warehouse Multiclass.csv")
df.head()

,composite_key,age_level,gender,bmi_level,smoking,diabetes,age,age_normalized,bmi,hypertension,...,salt_intake,heart_rate,hdl,ldl,education_level,employment_status,source_dataset,disease_flags,sublabel,label
0,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,9,0.080460,19.20,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
1,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,22.55,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
2,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,22.89,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
3,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,23.12,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
4,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,4,0.022989,19.61,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal

In [4]:
# finding misssing values

df.isnull().sum()

composite_key           0
age_level               0
gender                  0
bmi_level               0
smoking                 0
diabetes                0
age                     0
age_normalized          0
bmi                     0
hypertension            0
heart_disease           0
HbA1c_level             0
glucose                 0
cholesterol             0
sleep_hours             0
triglycerides           0
physical_activity       0
family_history          0
stress_level            0
low_hdl_cholesterol     0
high_ldl_cholesterol    0
blood_pressure          0
high_blood_pressure     0
sugar_consumption       0
crp_level               0
homocysteine_level      0
systolic_bp             0
diastolic_bp            0
alcohol_intake          0
salt_intake             0
heart_rate              0
hdl                     0
ldl                     0
education_level         0
employment_status       0
source_dataset          0
disease_flags           0
sublabel                0
label                   0
dtype: int64

In [10]:
# check any duplicates present or not

df.duplicated().sum()

# checking which cols has ho many duplicates i want numbers

df[df.duplicated(keep=False)].groupby(list(df.columns)).size().reset_index(name='count').sort_values(by='count', ascending=False).head(10)

,composite_key,age_level,gender,bmi_level,smoking,diabetes,age,age_normalized,bmi,hypertension,...,heart_rate,hdl,ldl,education_level,employment_status,source_dataset,disease_flags,sublabel,label,count
286,Mature_Female_Overweight_Never_No,Mature,Female,Overweight,Never,No,59,0.655172,27.32,0.0,...,74.766029,64.934758,131.125984,Secondary,Unemployed,diabetes,"0,0,0",N,Normal,3
621,Middle_Female_Overweight_Former_No,Middle,Female,Overweight,Former,No,34,0.367816,27.32,0.0,...,75.122034,64.197740,129.983051,Primary,Employed,diabetes,"0,0,0",N,Normal,3
712,Middle_Female_Overweight_Never_No,Middle,Female,Overweight,Never,No,26,0.275862,27.32,0.0,...,74.022857,64.889143,130.259429,Secondary,Employed,diabetes,"0,0,0",N,Normal,3
486,Mature_Male_Overweight_Never_No,Mature,Male,Overweight,Never,No,52,0.574713,27.32,0.0,...,74.056883,65.304892,129.050057,Tertiary,Retired,diabetes,"0,0,0",N,Normal,3
30,Mature_Female_Overweight_Former_No,Mature,Female,Overweight,Former,No,63,0.701149,27.32,0.0,...,74.972428,65.073171,128.567338,Secondary,Unemployed,diabetes,"0,0,0",N,Normal,3
641,Middle_Female_Overweight_Former_No,Middle,Female,Overweight,Former,No,45,0.494253,27.32,0.0,...,75.122034,64.197740,129.983051,Primary,Employed,diabetes,"0,0,0",N,Normal,3
462,Mature_Male_Overweight_Never_No,Mature,Male,Overweight,Never,No,49,0.540230,27.32,0.0,...,74.056883,65.304892,129.050057,Tertiary,Retired,diabetes,"0,0,0",N,Normal,3
117,Mature_Female_Overweight_Never_No,Mature,Female,Overweight,Never,No,49,0.540230,27.32,0.0,...,74.766029,64.934758,131.125984,Secondary,Unemployed,diabetes,"0,0,0",N,Normal,3
243,Mature_Female_Overweight_Never_No,Mature,Female,Overweight,Never,No,56,0.620690,27.32,0.0,...,74.766029,64.934758,131.125984,Secondary,Unemployed,diabetes,"0,0,0",N,Normal,3
163,Mature_Female_Overweight_Never_No,Mature,Female,Overweight,Never,No,52,0.574713,27.32,0.0,...,74.766029,64.934758,131.125984,Secondary,Unemployed,diabetes,"0,0,0",N,Normal,3

In [ ]:
# data cleaning process

# change encoding to numeric

df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})

In [11]:
import pandas as pd
import numpy as np


class DataCleaner:

    def __init__(self, df):
        self.df = df.copy()

    # -------------------------------------------------
    # 1. Standardize column names
    # -------------------------------------------------
    def standardize_columns(self):

        self.df.columns = (
            self.df.columns
            .str.strip()
            .str.lower()
            .str.replace(" ", "_")
        )

        return self


    # -------------------------------------------------
    # 2. Remove duplicate records
    # -------------------------------------------------
    def remove_duplicates(self):

        before = len(self.df)

        self.df.drop_duplicates(inplace=True)

        after = len(self.df)

        print(f"Duplicate rows removed: {before - after}")

        return self


    # -------------------------------------------------
    # 3. Remove identifier
    # -------------------------------------------------
    def drop_identifier(self):

        self.df.drop(
            columns=["composite_key"],
            errors="ignore",
            inplace=True
        )

        return self


    # -------------------------------------------------
    # 4. Standardize categorical text
    # -------------------------------------------------
    def clean_text_columns(self):

        cols = self.df.select_dtypes(include=["object", "string"]).columns

        for col in cols:

            self.df[col] = (
                self.df[col]
                .astype("string")
                .str.strip()
                .str.lower()
            )

        return self


    # -------------------------------------------------
    # 5. Missing values
    # -------------------------------------------------
    def handle_missing_values(self):

        numeric_cols = self.df.select_dtypes(
            include=np.number
        ).columns

        categorical_cols = self.df.select_dtypes(
            include=["object", "string", "category"]
        ).columns

        # Numerical -> Median
        for col in numeric_cols:

            self.df[col] = self.df[col].fillna(
                self.df[col].median()
            )

        # Categorical -> Mode
        for col in categorical_cols:

            mode = self.df[col].mode(dropna=True)

            if not mode.empty:
                self.df[col] = self.df[col].fillna(mode.iloc[0])

        return self


    # -------------------------------------------------
    # 6. Convert numeric-looking columns
    # -------------------------------------------------
    def convert_numeric_columns(self):

        numeric_cols = [
            "age",
            "age_normalized",
            "bmi",
            "hba1c_level",
            "glucose",
            "cholesterol",
            "sleep_hours",
            "triglycerides",
            "crp_level",
            "homocysteine_level",
            "systolic_bp",
            "diastolic_bp",
            "alcohol_intake",
            "salt_intake",
            "heart_rate",
            "hdl",
            "ldl"
        ]

        for col in numeric_cols:

            if col in self.df.columns:

                self.df[col] = pd.to_numeric(
                    self.df[col],
                    errors="coerce"
                )

        return self


    # -------------------------------------------------
    # 7. Binary Encoding
    # -------------------------------------------------
    def encode_binary_columns(self):

        binary_mapping = {
            "yes": 1,
            "no": 0,

            "true": 1,
            "false": 0,

            "positive": 1,
            "negative": 0,

            "male": 1,
            "female": 0
        }

        binary_cols = [
            "gender",
            "smoking",
            "diabetes",
            "hypertension",
            "heart_disease",
            "family_history",
            "low_hdl_cholesterol",
            "high_ldl_cholesterol",
            "high_blood_pressure"
        ]

        for col in binary_cols:

            if col in self.df.columns:

                # Only mapping strings.
                # Existing 0/1 values remain unchanged.
                if not pd.api.types.is_numeric_dtype(self.df[col]):

                    self.df[col] = (
                        self.df[col]
                        .astype("string")
                        .str.strip()
                        .str.lower()
                        .replace(binary_mapping)
                    )

                    self.df[col] = pd.to_numeric(
                        self.df[col],
                        errors="coerce"
                    )

        return self


    # -------------------------------------------------
    # 8. Ordinal Encoding
    # -------------------------------------------------
    def encode_ordinal_columns(self):

        # Age category
        age_mapping = {
            "young": 0,
            "adult": 1,
            "middle_age": 2,
            "middle aged": 2,
            "middle-aged": 2,
            "senior": 3,
            "elderly": 3
        }

        # BMI category
        bmi_mapping = {
            "underweight": 0,
            "normal": 1,
            "normal weight": 1,
            "overweight": 2,
            "obese": 3,
            "obesity": 3
        }

        # Stress
        stress_mapping = {
            "low": 0,
            "medium": 1,
            "moderate": 1,
            "high": 2
        }

        # Physical activity
        activity_mapping = {
            "low": 0,
            "medium": 1,
            "moderate": 1,
            "high": 2
        }

        # Blood pressure category
        bp_mapping = {
            "normal": 0,
            "elevated": 1,
            "high": 2,
            "hypertension": 2
        }

        mappings = {
            "age_level": age_mapping,
            "bmi_level": bmi_mapping,
            "stress_level": stress_mapping,
            "physical_activity": activity_mapping,
            "blood_pressure": bp_mapping
        }

        for col, mapping in mappings.items():

            if col in self.df.columns:

                # Don't touch already numerical encoding
                if not pd.api.types.is_numeric_dtype(self.df[col]):

                    self.df[col] = (
                        self.df[col]
                        .astype("string")
                        .str.strip()
                        .str.lower()
                        .map(mapping)
                    )

        return self


    # -------------------------------------------------
    # 9. Validate Encoding
    # -------------------------------------------------
    def check_remaining_categories(self):

        categorical_cols = self.df.select_dtypes(
            include=["object", "string", "category"]
        ).columns.tolist()

        print("\nRemaining categorical columns:")

        if categorical_cols:

            for col in categorical_cols:

                print(f"\n{col}")

                print(
                    self.df[col]
                    .value_counts(dropna=False)
                    .head(20)
                )

        else:

            print("No categorical columns remaining.")

        return self


    # -------------------------------------------------
    # Complete cleaning pipeline
    # -------------------------------------------------
    def clean(self):

        self.standardize_columns()

        self.remove_duplicates()

        self.drop_identifier()

        self.clean_text_columns()

        self.convert_numeric_columns()

        self.encode_binary_columns()

        self.encode_ordinal_columns()

        # Run after conversion/encoding because those operations
        # may create NaN for invalid values.
        self.handle_missing_values()

        self.check_remaining_categories()

        return self.df

In [12]:
df.head()

,composite_key,age_level,gender,bmi_level,smoking,diabetes,age,age_normalized,bmi,hypertension,...,salt_intake,heart_rate,hdl,ldl,education_level,employment_status,source_dataset,disease_flags,sublabel,label
0,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,9,0.080460,19.20,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
1,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,22.55,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
2,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,22.89,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
3,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,23.12,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
4,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,4,0.022989,19.61,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal

In [15]:
df['bmi_level'].value_counts()

bmi_level
Obese          98377
Overweight     79172
Normal         70596
Underweight    32840
Name: count, dtype: int64